VlachosGroup/AIMSim

- molecular_similarity.py
Add x and y label to the pdf plot of compare_taraget_molecule
> Fix pdf target molecule

- molecular_similarity.py
Fix Bug: identify_closest_furthest output does not show name of target_molecule
> Fix Issue #5

- molecular_similarity.py
Fix bug " identify_closest_furthest chooses the target molecule in the database itself as the closest match"
> Bugfix-Issue#6

- config.yaml
- molecular_similarity.py
- output_jazz.txt
> Feature set name output file

- config.yaml
- molecular_similarity.py
config now has a verbose modifier to suppress non-error related print statements. plots are now all generated without pausing execution. Both of these changes make large-scale comparisons more practical.
> added verbose option, plots now run without pausing execution

- README.md
- molSim/exceptions.py
- molSim/ops/descriptor.py
- tests/test_Descriptor.py
- support for mordred descriptors added in descriptor.py
- custom exception added for issues with mordred
- added test for some Mordred descriptors
- update README
This PR should resolve #79
> add support for mordred

- molSim/tasks/cluster_data.py
- molSim/tasks/compare_target_molecule.py
- molSim/tasks/show_property_variation_with_similarity.py
Create directories of output files if not present
> Fix Issue #85

- molSim/tasks/cluster_data.py
- molSim/tasks/compare_target_molecule.py
- molSim/tasks/identify_outliers.py
- molSim/tasks/show_property_variation_with_similarity.py
- molSim/tasks/visualize_dataset.py
config_reader throws err if task has no configs (issue for tasks with optional parameters)
> Solve issue #84

- molSim/chemical_datastructures/molecule.py
- molSim/chemical_datastructures/molecule_set.py
- molSim/ops/descriptor.py
Address issue #92 
Add support to choose radius in Morgan fingerprint for consistency with ECFP #92
> Read fingerprint_params from config to modify fingerprint defaults

- molSim/tasks/visualize_dataset.py
- molSim/utils/plotting_scripts.py
> Change default to show entire similarity heatmap 

- README.md
- molSim/ops/descriptor.py
- molSim/utils/ccbmlib_fingerprints.py
this PR adds the fingerprints from the ccbmlib library. This is not available on pypi, so I have cherry picked the necessary code and added it to the repo.
> add more fingerprints

- molSim/chemical_datastructures/molecule_set.py
- molSim/tasks/cluster_data.py
- molSim/utils/plotting_scripts.py
> Add feature plot property distribution plots with clustering

- molSim/chemical_datastructures/molecule_set.py
- molSim/ops/clustering.py
Add clustering methods. Solve issue #135
> Add single linkage, average linkage and ward algorithms

- molSim/tasks/see_property_variation_with_similarity.py
- molSim/tasks/visualize_dataset.py
Import plt from matplotlib not plotting_script
> Import plt from matplotlib.pyplot not plotting_scripts

- tests/test_MeasureSearch.py
explores combinations of fixing fingerprint and similarity measure (as well as only_metric). Related to #166
> new tests for measure search

- AIMSim/utils/plotting_scripts.py
> Solve empty handles passed for legends

- .github/workflows/check_pypi_build.yml
- AIMSim/tasks/cluster_data.py
- AIMSim/tasks/identify_outliers.py
- AIMSim/tasks/visualize_dataset.py
- AIMSim/utils/plotting_scripts.py
- requirements.txt
- tests/test_TaskManager.py
> Add interactive scatter plots for scatter plots

- aimsim/tasks/cluster_data.py
so default colors can be used by plotly
> Change default cluster colors from cmap to hex 

- aimsim/ops/similarity_measures.py
> use lru_cache for speedup and compatibility

- aimsim/tasks/cluster_data.py
- aimsim/tasks/compare_target_molecule.py
- aimsim/tasks/see_property_variation_with_similarity.py
- aimsim/tasks/task_manager.py
- aimsim/tasks/visualize_dataset.py
- aimsim/utils/plotting_scripts.py
- interfaces/UI/AIMSim_ui_main.py
Issue #170 describe figures not being properly generated under certain circumstances, this PR fixes the issue by removing `plt.show()` in all but one central location.
> Figures not displaying correctly fix

- aimsim/tasks/task_manager.py
check for valid_dist irrespective of fingerprint or similarity_measure set to determine
> fix issue #244 

- .github/workflows/mordred_check.yml
- README.md
- aimsim/__init__.py
- aimsim/ops/descriptor.py
- aimsim/utils/extras.py
- setup.py
> Optional `mordred` Install Cleanup and Documentation

- aimsim/__init__.py
- aimsim/ops/clustering.py
the affinity keyword has been deprecated - this adds a workaround
> Update clustering.py for compatibility with latest sklearn

- aimsim/__init__.py
- aimsim/tasks/visualize_dataset.py
> Fix Missing import of `warnings` Inside `visualize_dataset.py`

- AIMSim-demo.ipynb
- aimsim/__init__.py
- aimsim/chemical_datastructures/molecule_set.py
- aimsim/ops/clustering.py
- examples/Wang-et-al-log-partition-coefficients/config_logP.yaml
- requirements.txt
- requirements_core.txt
- tests/test_MoleculeSet.py
Sklearn_extra has been abandoned and no lonber works with Python 3.12 - remove it for the future's sake.
> Drop k-medioids Clustering

- .github/workflows/ci.yml
- aimsim/__init__.py
- aimsim/ops/descriptor.py
- tests/test_Descriptor.py
First mentioned here: https://github.com/JacksonBurns/fastprop/issues/20
> Fix MorganGenerator Deprecation Warning
